---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: __CI_PROJECT_NAME__
    ref: __CI_ENVIRONMENT_NAME__
  name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_NAME__
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __CI_PROJECT_NAME__
      ref: __CI_ENVIRONMENT_NAME__
  template:
    metadata:
      labels:
        app: __CI_PROJECT_NAME__
        ref: __CI_ENVIRONMENT_NAME__
    spec:
      containers:
      - image: 172.31.140.12:8888/ywdev/__CI_PROJECT_NAME__:__CI_ENVIRONMENT_NAME__
        imagePullPolicy: Always
        name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_NAME__
        command:
          - "./run"
        ports:
        - containerPort: 5050
          name: http
        - containerPort: 5040
          name: grpc
        # env:
        #   - name: http_proxy
        #     value: http://172.31.170.2:13080
        #   - name: https_proxy
        #     value: http://172.31.170.2:13080
        #   - name: no_proxy
        #     value: 10.108.0.0/16,127.0.0.1/32,localhost,local
        volumeMounts:
          - name: config-volume
            mountPath: /app/server/{{.Name}}server/conf/conf.yaml
            subPath: conf.yaml
      volumes:
        - name: config-volume
          configMap:
            name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_NAME__
            items:
              - key: config.yaml
                path: config.yaml
                mode: 0755
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux


---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: __CI_PROJECT_NAME__
    ref: __CI_ENVIRONMENT_NAME__
  name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_NAME__
  namespace: __NAMESPACE__
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 5050
  selector:
    app: __CI_PROJECT_NAME__
    ref: __CI_ENVIRONMENT_NAME__

