# relative path for code generation
target:
  relativeDir:
    project:
      - ""
    proto:
      - "pkg"
      - "{GROUP_NAME}"
      - "{SERVICE_NAME}"
    client:
      - "pkg"
      - "{GROUP_NAME}"
      - "{SERVICE_NAME}"
    server:
      - "services"
      - "{GROUP_NAME}"
      - "{SERVICE_NAME}server"
template:
  filesFormatSuffix: ".tmpl"
  protoFilename: "{SERVICE_NAME}.proto.tmpl"
  relativeDir:
    project:
      - "project"
    proto:
      - "proto"
    client:
      - "client"
    server:
      - "server"

